### ISSUE TITLE
[RFE] Support encrypted partitions

### ISSUE THREAD

**Issue by e-minguez** [daniel-thompson/pinebook-pro-debian-installer#1]
It would be nice for the installer to be able to use LUKS to install Debian in an encrypted disk.

**Comment by daniel-thompson** [comment]
I haven't added any docs for it yet, because the implementation is a bit of a hack, but if you want an encrypted rootfs try the following (adding a MMCBLK= if required):

  make CRYPT=crypt

Note that this will require that you are running a kernel that can mount encrypted file systems. Note that the factory (Debian Stretch) distro did not originally support that. I saw there were new, more feature rich kernel, available in the v1.5 and v1.6 updates though.

In the worst case the kernel that this installer uses does support encryption (obviously) so if needed you can use the installer to build a non-encrypted system and then use that non-encrypted system to construct an encrypted one ;-).

**Comment by e-minguez** [comment]
A few things:

* `cryptsetup` is not installed in the official debian release (it would be nice to check it before formatting the filesystem :D)
* It failed to me as:

```
...
sudo cryptsetup luksFormat /dev/mmcblk1p6

WARNING!
========
This will overwrite data on /dev/mmcblk1p6 irrevocably.

Are you sure? (Type uppercase yes): YES
Enter passphrase: 
Verify passphrase: 
sudo cryptsetup open /dev/mmcblk1p6 RootFS
Enter passphrase for /dev/mmcblk1p6: 
device-mapper: reload ioctl on RootFS failed: Invalid argument
Makefile:62: recipe for target 'cryptmkfs' failed
make: *** [cryptmkfs] Error 1
```

dmesg says:

```
[  830.448882]  mmcblk1: p1 p2 p3 p4 p5 p6
[  830.600810]  mmcblk1: p1 p2 p3 p4 p5 p6
[  867.455515] device-mapper: table: 252:0: crypt: unknown target type
[  867.455526] device-mapper: ioctl: error adding target to table
```
So I'm assuming this is the aforedmention module missing, so I've opened https://github.com/mrfixit2001/debian_desktop/issues/24

**Comment by daniel-thompson** [comment]
Thanks. We can (and should) add cryptsetup to the prerequisites command but the later problem with device-mapper is a kernel feature that is not enabled in v4.4 which means we cannot get around it (I test encrypted installs from a distro I bootstrapped using my installer so I have a kernel with more features enabled).

PS Over the holiday period I hope to find time to rewrite in something that isn't make. I like make for early hacking and proof-of-concepts because it is so easy to run and re-run internal steps. However the installer seems to be working well enough that we are well past the proof-of-concept stage ;-).

**Comment by dofishswim** [comment]
Thanks a lot @daniel-thompson , this is great :) 
FWIW, it is working fine from the latest Manjaro ARM by replacing `apt-get install -y` by `pacman -Syu` on https://github.com/daniel-thompson/pinebook-pro-debian-installer/blob/master/Makefile#L26

The PATH need update as following for some of the chroot command line:
```
PATH=$PATH:/usr/sbin
make CRYPT=crypt
```
PS: currently the script cannot be re-run from Debian itself due to `RootFS` being hardcoded and conflicting with the existing one, let me know and i can open a separate issue ab it...

Peace

**Comment by daniel-thompson** [comment]
Hi @dofishswim ,

Thanks for the info. I didn't realize the script could not run from itself (there would be boot problems if both media are present at the same time... this is mentioned in the Limitations), perhaps I have acidentally used a partition label rather than a fully qualified device path somewhere.

Either way no need to file an issue since it will get fixed when the documentation limitation is removed.

**Comment by daniel-thompson** [comment]
The addition of templating (part of the port to shell script) means that installs from installs should now work without problem and LUKS support is now documented in the README.

I think we can close this one now.

**Comment by e-minguez** [comment]
Thanks!
