### ISSUE TITLE
Something broke a couple weeks ago

### ISSUE THREAD

**Issue by ab1jx** [daniel-thompson/pinebook-pro-debian-installer#15]
I had this installed once 1/15/2020, liked it, but screwed it up after a week or two.  I've been trying to reinistall it ever since, and so have a few other people https://forum.pine64.org/showthread.php?tid=8915&pid=60428#pid60428 so somebody filed a Debian bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949980

I suspect the problem isn't libgl1-mesa-dri at all but I haven't looked at it with gdb.  Somewhere there's a segfault, in my case in starting xorg.

[code]
[   194.588] (II) event1  - gpio-keys: is tagged by udev as: Keyboard Switch
[   194.588] (II) event1  - gpio-keys: device is a keyboard
[   194.588] (II) event1  - gpio-keys: device is a switch device
[   197.152] (EE)
[   197.152] (EE) Backtrace:
[   197.155] (EE) 0: /usr/lib/xorg/Xorg (OsLookupColor+0x188) [0xaaaacf2208a0]
[   197.155] (EE) unw_get_proc_info failed: no unwind info found [-10]
[   197.155] (EE)
[   197.155] (EE) Segmentation fault at address 0xaadad3a895f8
[   197.155] (EE)
Fatal server error:
[   197.155] (EE) Caught signal 11 (Segmentation fault). Server aborting
[   197.155] (EE)
[   197.155] (EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
[/code]

I've tried the latest version of libgl1-mesa-dri from unstable, the one in experimental requires gcc 10.  I'd like to look at a database listing of debs in Bullseye updated in the last 45 days and intersect it with files I have.  I'm not sure that capability exists, I don't think there is an SQL database anywhere.

**Comment by daniel-thompson** [comment]
This looks like it is a problem in the upstream packages rather than the installer or kernel so the upstream bug tracker is the appropriate place to track this (and the issue is already listed on the wiki: https://wiki.pine64.org/index.php/Pinebook_Pro_Debian_Installer ).

Note that mesa-20 was recently released so there should be a good chance of panfrost fixes making it into bullseye/sid fairly shortly.

Note I recently added support for RELEASE=buster into the installer. I think this will side step the problem because mesa in buster is too old to have any panfrost code it is (meaning OpenGL will be handled by the llvmpipe software implementation instead).

**Comment by ab1jx** [comment]
Thank you, yes, the flexibility to change releases is what I was looking for (I tried, didn't work).  There's a time in almost every machine's lifetime for a debootstrap script but most are more closely coupled to the hardware (drivers & firmware) than to the release.  Since this is essentially a "Production Machine", Bullseye is out of the picture for now.  I plan to start with Vulkan from sources, the GPU is supported by Vulkan.

**Comment by ab1jx** [comment]
Could this be fixable by installing the latest panfrost/mesa from source if needed?  I prefer to do that anyway with stuff that changes faster than the debs keep up like ffmpeg and youtube-dl.  Just partitioning my SSD and wondering if Bullseye might work now.

**Comment by daniel-thompson** [comment]
Yes, if you want to run a Debian Buster machine except for XYZ then building from source is fine.
