### ISSUE TITLE
Problem during installation (policykit)

### ISSUE THREAD

**Issue by fsfboy78** [daniel-thompson/pinebook-pro-debian-installer#34]
Hi Daniel,

I'm trying to install Debian Bullseye with your script on my Pinebook Pro, but I get this error :

...
I: Configuring plymouth-themes...
I: Configuring tasksel-data...
I: Configuring tasksel...
I: Configuring libc-bin...
I: Configuring ca-certificates...
I: Configuring initramfs-tools...
I: Configuring dbus...
W: Failure while configuring base packages.  This will be re-attempted up to five times.
W: See /home/fsfboy/pinebook-pro-debian-installer/sysimage/debootstrap/debootstrap.log for details (possibly the package policykit-1 is at fault)
W: Failure while configuring base packages.  This will be re-attempted up to five times.
W: See /home/fsfboy/pinebook-pro-debian-installer/sysimage/debootstrap/debootstrap.log for details (possibly the package policykit-1 is at fault)
W: Failure while configuring base packages.  This will be re-attempted up to five times.
...

Do you have any idea where this error could come from? and how to resolve the problem?

Thank you for your help :)

**Comment by ghost** [comment]
I don't know of a solution. I'm facing the same problem myself.

I reckon later tonight I'll go back to an older commit and see if it works. I'll touch base if it does

# EDIT
Since polkit-1 is pulled as a dependency of NetworkManager,  I prevented it from being automatically installed by editing "install-debian" and removing it from line 170 (function do_real_bootstrap)

I've successfully gotten to the ncurses install menu and avoided any polkit related errors. I'll edit this reply again if my system installs correctly

# WHOOP WHOOP
It works now.
You'll have to manually setup your networking using wpa_supplicant and dhclient

**Comment by fsfboy78** [comment]
Problem solved by deleting "network-manager" on line 170 of the install-debian script.

Thanks to isalic8 for his help :)
