### ISSUE TITLE
Request to list all non-free components (and any ways to exclude them if possible)

### ISSUE THREAD

**Issue by nickbailuc** [daniel-thompson/pinebook-pro-debian-installer#39]
Apologize if this is a little informal. I'd like to request, if possible, a list of non-free binary blobs, drivers, firmware in the readme, or as a separate file. Many who use Debian use it because of its philosophy of excluding non-free components where they aren't necessary.

I am aware that the WiFi and Bluetooth drivers are both non-free. Possibly the best free Bluetooth chip is the CSR8510 which is usually a USB dongle. I already have this installed, however am unable to disable/purge the non-free firmware/driver for the built-in module (usually a `udev` exception can be made, however `lspci` doesn't list anything on arm64 computers it seems). Is there another way the non-free driver can be removed?

I'd also like to ask, the custom kernel that is used, does it have any non-free components, or is it custom because it is tailed to boot on the pinebook-pro (in other words, is it possible to use the Debian mainline kernel from testing repo)

I'm making this issue as a request to include a file listing all the non-free components that the script installs. If there is a section under this project under which this request fits more appropriately, I would be happy to move it there.

The staff of the Free Software Foundation is evaluating the pinebook-pro for its 'freedom' (the list of things under question can be found on libreplanet). The first major leap to make this happen would be to confirm if there is a distro that is fully free that can run on the pinebook-pro.

Thanks in advance!

**Comment by daniel-thompson** [comment]
I think all firmware in ap6256-firmware and pinebook-firmware should be treated as nonfree unless there is anything specific in these repos that indicates otherwise.

Beyond that I am not aware of any other nonfree software that will be picked up by the installer. The kernel is built from the upstream Linux repos with a small number of GNU GPL patches applies on top.

However, I don't really have any plans to update the README because (as mentioned in the [roadmap](https://github.com/daniel-thompson/pinebook-pro-debian-installer#roadmap) the installer is now very close to end of life. This installer will very soon be obsolete because we can boot the real Debian installer instead (assuming the correct bootloaders are installed first). For more details see https://forum.pine64.org/showthread.php?tid=14109 .
